project:
  type: website
  output-dir: docs
  

website:
  title: "Home"
  sidebar:
    search: true
    contents: 
      - section: "Projects"
        contents: 
          - BuildWorld.qmd
          - SIMIODES.qmd

format: 
    html:
        theme: morph
        code-fold: true
        toc: true