project:
  type: website
  output-dir: docs
  

website:
  title: "Home"
  sidebar:
    search: true
    contents: 
      - section: "Projects"
        contents: 
          - BuildWorld.qmd
          - SIMIODES.qmd
          - GameOfLife.qmd
          - text: Cal Hacks 9.0
            url:  https://devpost.com/software/asl-quick-learn
            
      - section: "Resume"
        contents:
          - resume.qmd

format: 
    html:
        theme: morph
        code-fold: true
        toc: true